import type { Metadata } from "next";
import {GlobalStyle} from "@/app/component/GeneralStyles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalStyle />
      <body >{children}</body>
    </html>
  );
}
